name: Generate Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run main.py scripts
      run: |
        for main_script in $(find . -type f -name "main.py"); do
          dir=$(dirname "$main_script")
          # Exclude root main.py if it exists, and scripts folder
          if [ "$dir" != "." ] && [ "$dir" != "./scripts" ]; then
            echo "Running main.py in $dir"
            (cd "$dir" && PYTHONPATH=.. python main.py)
          fi
        done

    - name: Package XML files
      run: zip release-artifacts.zip **/*.xml

    - name: Upload XML artifacts
      if: github.event_name != 'release'
      uses: actions/upload-artifact@v4
      with:
        name: generated-xml-files
        path: '**/*.xml'

    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./release-artifacts.zip
        asset_name: release-artifacts.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
